spring:
  application:
    name: cloud-provider-user-feign
server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix: 
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 
